### PR TITLE
Add item cards

### PR DESCRIPTION
**Pull request by fschwaiger**
Implemented `ItemCardLayout` and `SmallItemCard` analogous to monster cards.

- [x] needs placeholder image that is free to use
- [x] noticed the artist name was too small (was this on purpose?) - set to 1.5mm
- [x] noticed the top border of small cards was less than the min border, which I doubt is intentional - set to 2.5mm

### CODE REVIEW

**Comment by ep1cman** [comment]
You sir are a legend! You beat me to it 😄 Thank you for starting this work.

1. I will work on a placeholder image and share it with you. The official cards use a image of a book with gems, a wand and a scroll on top of it, but we can't scan that for copyright reasons, and my artisitc skills can't recreate it. I will make something similar to the moster icon, maybe taking inspiration from dndbeyond.
2. The new artist name size looks fine to me, thanks for fixing
3. Believe it or not, the single side cards (at least the ones I have) the back top border is that small. I need to remind myself why the code even has a `minimum` size. Quite honestly, I might do away with trying to match the peculiarities of the print cards and make the designs more consistent.

Some additional tasks that will need to be done:
- [ ] Document how to make item cards
- [ ] Process SRD and create example YAML

How would you like to collaborate on this, should I raise PRs into your fork?

**Comment by fschwaiger** [comment]
- [ ] note to self: with added top border, the title must mode down as well

**Comment by ep1cman** [comment]
I have added a placeholder for items

**Comment by ep1cman** [comment]
I've produced a (rough) dataset of SRD items for us to test with. A few notes about it:
1. The description field hasn't been fully processed so some are badly formatted
2. The source dataset is missing the subtitle data, so that would have to be manually added sadly
[compendium.item.zip](https://github.com/ep1cman/DnD-Card-Generator/files/7657020/compendium.item.zip)

Some things I've already spotted:
- [ ] The official cards do not resize title text, they instead flow it onto extra rows 
- [ ] Sub categories will also need to flow
- [ ] The official cards don't feature an artist on the front - I'm not sure if we should or shouldn't copy them

Also, white pages appear when cards don't fit (This is bug in the main code, not yours - #24)

**Comment by ep1cman** [comment]
2CE79CC1-E2FB-4129-AB3E-7191910369F0
Should we copy their typesetting mistakes too? 😂

**Comment by fschwaiger** [comment]
- The cards I have say "Art: xxxxxx" on the front. With the artist field being optional (not sure whether this is currently the case), it can be left out if need be.
- The formatting should be no copy, just be consistent I think. I like to see the tool as an option to typeset additional Homebrew cards. That said I have no direct interest in contributing to the SRD file.
- Double row titles are maybe not worth the effort. Later we should open another (optional) issue ticket I think.

- [ ] some cards have actions, we should copy the actions typesetting mechanism from MonsterCardLayout

**Comment by ep1cman** [comment]
Thats good news about the art, it felt like a weird ommission on the item cards. Must be something they fixed in a later printing. I am happy to keep it.

I have looked through the item cards to see how actions are presented and found the following:
- Regular actions:
actions
- Actions without descriptions:
action without description
- Multiple actions without descriptions:
multiple bold

I propose we use a similar format to legendary actions:

  ```
  - Some regular text
  - Action: description
  - Action without descrption:
  - Some more text
  ```

There are some other features I found on the cards:

- Horizontal rule
line
This seems exclusive to the ioun stones, so I don't think its needed in this tool

- Bullet points
bullets
Easily done by just using the `•` symbol in text.

- Single table
table
I have no idea how to represent this in either YAML or Reportlab. I propose this as being out of the scope of the PR.

- Double column table
two column table
Similar to above but presented with a break in the middle to fit a long narrow table into less vertical space

- Source on long cards
card with source
Many items with descriptions to long to fit simply contain a reference on where the full information can be found. I suggest we use the `source` field like on monster cards, and add this to the end of the text if present

**Comment by ep1cman** [comment]
I just rebased the PR on the latest master

**Comment by ep1cman** [comment]
Could you explain the following snippet of code?
```
        # item cards have more padding at the top than moster cards
        self.frames[0]._y2 += 1 * mm
```
Is the intention of this to lower the text to increase the space between the red subtitle bar and the item card main text?
The actual effect it seems to be having is moving the title and subtitle upwards which seems like a bug in the original layout code

**Comment by fschwaiger** [comment]
> Could you explain the following snippet of code?
> [ ... ]
> Is the intention of this to lower the text to increase the space between the red subtitle bar and the item card main text? The actual effect it seems to be having is moving the title and subtitle upwards which seems like a bug in the original layout code

It felt like a waste to completely redefine the Frame, when 95% of the calculations remain the same. Just wanted to increase top padding, but padding was not editable. Moving the top frame edge had this nasty side effect you mention.

I like your fix better. Can you please also remove the dangling comment line 978?

**Comment by ep1cman** [comment]
Ok I managed to get the multi line titles working today. The back was relatively easy but reworking the front required some rather nasty hacking of reportlab. A friend also created an example item out of my test data 😂 
The final result:
image

I am happy to leave tables and the SRD out of this PR, meaning the only thing left to do is documentation and testing.

I would appreciate it if you could test this out to see if it works as you expected

**Comment by fschwaiger** [comment]
The layout looks nice to me!

**Pull request merged**
