### PR TITLE
Format abilities and action headers differently

### PR DESCRIPTION
**Pull request by fschwaiger**
Might be intended on your side, but I find cursive for abilities and a dot instead of colon to be a closer match.

### CODE REVIEW

**Comment by ep1cman** [comment]
Good spot on the `.` vs `:`! 

However the italics vs bold italics is an interesting case. The official cards actually use both styles. The original ones used just italics for the abilities, the newer ones used bold italics like they do for the actions etc.

Personally I prefer the bold just because it makes it easier to glance down and spot them

**Comment by fschwaiger** [comment]
1) reverted the non-bold heading to be bold again.
2) not sure on the legendary actions, the font did overlap on my card, but as `text` was fine.

**Comment by ep1cman** [comment]
Can you share a screenshot of the overlapping on the legendary actions? The official "epic" monster cards specifically don't have gaps around the legendary actions as they do the regular actions. I believe this is in an effort to save space as a lot of the cards with legendary actions get very close to the size of the card.
Upon closer inspection there is quite a lot of inconsistency in the type setting, I have noticed some are typeset:
```
**Name**:Some long text
some other long text
```
while others are typeset with indents
```
**Name**:Some long text
   some other long text
```

So ultimately this comes down to A) The typesetting of this tool always being functional (which with an overlap it wouldn't be) and B) How true to the original we want it to stay

It might be interesting to see how many cards fail to fit with the extra spacing

**Comment by fschwaiger** [comment]
This was what I noticed:

image

I agree if they are typeset with an indent, I should not break that. But it looks like a bug.

**Comment by ep1cman** [comment]
I have my email address on my github profile, can you reach out to me on that so we can share the YAML for debugging without sharing copyrighted materials on here

**Pull request merged**
