### PR TITLE
allow user to override card color

### PR DESCRIPTION
**Pull request by fschwaiger**
User can now specify any color other than red in the YAML file. This does not recolour the placeholder image.

### CODE REVIEW

**Comment by ep1cman** [comment]
Can you post an example of what this does?

**Comment by ep1cman** [comment]
image

**Comment by ep1cman** [comment]
I am happy with the functionality of this PR. Just one code style change I would ask for, rename `self.BORDER_COLOR` to `self.border_color` since it is no longer a constant value

**Comment by fschwaiger** [comment]
Sure!

**Pull request merged**
