### PR TITLE
add a section on bonus actions

### PR DESCRIPTION
**Pull request by fschwaiger**
Basically just duplicated the code snippet from actions.

### CODE REVIEW

**Comment by ep1cman** [comment]
Can you provide an example of a creature that needs this, would like to compare how the official cards implement it

**Comment by fschwaiger** [comment]
One creature I needed it for is the Tree Blight from Curse of Strahd.

**Comment by fschwaiger** [comment]
To be clear, the bonus action is not directly in the book, but I looked it up on dndbeyond and there it showed up as a bonus action as well. I guess this feature is not really needed then, good catch.

**Comment by ep1cman** [comment]
Ah I don't have that one on dndbeyond. Which action is its bonus action? 

If you find this on any other cards please post here, I would love to compare it to something I have a card of to see if they just ignored them

**Comment by ep1cman** [comment]
image
Looks like `abilities` are how bonus actions are represented with other tools like FightClub

**Pull request closed without merging**
